import { describe, expect, test } from 'bun:test';
import { run } from './day8';
import day8Input from './day8.input';

describe('Day 8', () => {
  describe('part 1', () => {
    test('test case', () => {
      const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;
      expect(run(input)).toBe(14);
    });

    test('real puzzle', () => {
      const result = run(day8Input);
      expect(result).toBe(254);
    });
  });
});

